version: '3.8'

services:
  additiond:
    build:
      context: ../../
      dockerfile: deploy/github-docker/Dockerfile
    container_name: additiond
    command: ["./build/additiond", "--network", "testnet", "--config", "config.toml"]
    ports:
      - "127.0.0.1:8545:8545"
      - "28545:28545"
      - "38545:38545"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
