version: '3.8'

services:
  additiond:
    build:
      context: ../../
      dockerfile: deploy/github-docker/Dockerfile
    container_name: additiond
    command: ["--network", "testnet", "--config", "config.toml"]
    ports:
      - "8545:8545"
      - "18545:18545"
      - "28545:28545"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
