#!/usr/bin/env python3
"""Run the live research-goal harness and write an honest markdown report.

Does not invent TPS, ZK-Shield circuits, public peers, or a DEX.
Contact: contact@additionblockchain.com
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "tests" / "test_research_goals.py"
REPORT = ROOT / "docs" / "RESEARCH_TESTNET_PROOF.md"


def status_label(status: str) -> str:
    mapping = {
        "pass": "PASS (real node)",
        "pass_mldsa_wrap": "PASS as ML-DSA wrap — not a ZK circuit",
        "partial": "PARTIAL — see exact reply",
        "recorded_failure": "RECORDED FAILURE — not faked as pass",
        "fail": "FAIL",
    }
    return mapping.get(status, status)


def _redact(value):
    if isinstance(value, dict):
        return {k: _redact(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_redact(v) for v in value]
    if isinstance(value, str) and len(value) > 240:
        return value[:96] + "...<%d chars redacted>..." % (len(value) - 192) + value[-96:]
    return value


def fmt_evidence(evidence: dict) -> str:
    lines = ["", "```text"]
    blob = json.dumps(_redact(evidence), indent=2, sort_keys=False)
    if len(blob) > 8000:
        blob = blob[:8000] + "\n... truncated for readability ..."
    lines.append(blob)
    lines.append("```")
    return "\n".join(lines)


def write_report(payload: dict, harness_rc: int) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    results = payload.get("results", [])
    by_goal = {item.get("goal"): item for item in results}

    def section(goal: str, title: str) -> str:
        item = by_goal.get(goal, {})
        return (
            "## %s\n\n"
            "- Result: **%s**\n"
            "- What happened: %s\n"
            "%s\n"
        ) % (
            title,
            status_label(str(item.get("status", "missing"))),
            item.get("detail", "harness did not produce this goal"),
            fmt_evidence(item.get("evidence") or {}),
        )

    body = """# Research testnet proof (honest)

This report was generated by `scripts/prove_research_goals.py` against a **real
local `additiond`**. It is a research testnet (`addition-testnet`), not a live
mainnet, not a token sale, and not a public peer list.

Contact: [contact@additionblockchain.com](mailto:contact@additionblockchain.com)

- Generated (UTC): `%s`
- Harness exit code: `%s`
- Ports: `%s`

How to reproduce:

```bash
cmake -S . -B build -DADDITION_BUILD_TESTS=ON
cmake --build build
ctest --test-dir build --output-on-failure
python3 scripts/prove_research_goals.py
```

Two local processes (localhost bootstrap only, no public peer IPs):

```bash
./scripts/start_two_node_testnet.sh
./scripts/stop_two_node_testnet.sh
```

P2P RPC stays off unless `ADDITION_ENABLE_P2P_RPC=1`. The start script and the
harness set that variable. They do not invent a public mesh.

---

%s
%s
%s
%s
%s
%s

## What this does **not** claim

- No invented TPS. `last_tps` is whatever `getinfo` printed (often `0.00` before
  a mine).
- No ZK-Shield / range-proof / Groth16 / Bulletproofs claim. If mint/spend
  succeeded, the node verified an **ML-DSA-87 signature of a public string**.
- No Uniswap, no fake DEX, no wallet-connect, no site redeploy, no token sale.
- EVM coverage is the existing bootstrap (`web/evm/evm_rpc_bridge.py`) only.
- `bridge_*` here is the in-process command surface, not a live foreign chain.

## Tests wired

CMake `ADDITION_BUILD_TESTS=ON` runs:

- `test_chain` (includes `min_fee=1` reject/accept)
- `test_privacy` (garbage proof rejected; ML-DSA wrap mint/spend)
- `test_rpc_access`
- `test_wallet`
- `test_public_rpc_two_node`
- `test_research_goals` (this live harness)
""" % (
        now,
        harness_rc,
        json.dumps(payload.get("ports", {})),
        section("quantum", "1. Quantum — ML-DSA-87 / pq_mode=strict"),
        section("privacy", "2. Privacy — privacy_mint_zk / privacy_spend_zk"),
        section("speed", "3. Speed — real getinfo fields only"),
        section("cost", "4. Cost — min_fee=1 reject/accept"),
        section("compatibility", "5. Compatibility — existing bridge_* + EVM bootstrap"),
        section("two_node", "Two local additiond processes"),
    )
    REPORT.write_text(body, encoding="utf-8")


def main() -> int:
    env = os.environ.copy()
    env.setdefault("ADDITIOND", str(ROOT / "build" / "additiond"))
    proc = subprocess.run(
        [sys.executable, str(HARNESS)],
        cwd=str(ROOT),
        env=env,
        capture_output=True,
        text=True,
    )
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    payload = {}
    for line in proc.stdout.splitlines():
        if line.startswith("{") and '"results"' in proc.stdout:
            start = proc.stdout.find("{")
            end = proc.stdout.rfind("}")
            if start >= 0 and end > start:
                try:
                    payload = json.loads(proc.stdout[start : end + 1])
                except json.JSONDecodeError:
                    payload = {"parse_error": True, "stdout": proc.stdout[-4000:]}
            break
    if not payload:
        payload = {
            "results": [
                {
                    "goal": "harness",
                    "status": "fail",
                    "detail": "harness produced no JSON (exit %s)" % proc.returncode,
                    "evidence": {"stderr": proc.stderr[-2000:]},
                }
            ]
        }
    write_report(payload, proc.returncode)
    print("wrote", REPORT)
    return 0 if proc.returncode == 0 else proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
